// Body Goals and Auto-Goal Generation for Melius

const BODY_PROFILE_KEY = 'melius-body-profile';
const AUTO_GOALS_KEY = 'melius-auto-goals';

export interface BodyProfile {
  age?: number;
  heightCm?: number; // Always stored in cm
  weightKg?: number; // Always stored in kg
  sex?: 'male' | 'female' | 'prefer_not_to_say';
  goal?: 'bulking' | 'cutting' | 'maintain';
  useImperial?: boolean; // For display preference
  createdAt?: number;
  updatedAt?: number;
}

export interface AutoGeneratedGoals {
  calories: number;
  protein: number;
  fiber: number;
  sugarLimit: number;
  generatedAt: number;
  acceptedAt?: number;
  basedOn: BodyProfile;
}

// Get body profile from localStorage
export function getBodyProfile(): BodyProfile | null {
  const stored = localStorage.getItem(BODY_PROFILE_KEY);
  if (!stored) return null;
  try {
    return JSON.parse(stored);
  } catch {
    return null;
  }
}

// Save body profile
export function saveBodyProfile(profile: Partial<BodyProfile>): BodyProfile {
  const existing = getBodyProfile() || {};
  const updated: BodyProfile = {
    ...existing,
    ...profile,
    updatedAt: Date.now(),
    createdAt: existing.createdAt || Date.now(),
  };
  localStorage.setItem(BODY_PROFILE_KEY, JSON.stringify(updated));
  return updated;
}

// Delete body profile
export function deleteBodyProfile(): void {
  localStorage.removeItem(BODY_PROFILE_KEY);
  localStorage.removeItem(AUTO_GOALS_KEY);
}

// Convert height from feet/inches to cm
export function feetToCm(feet: number, inches: number): number {
  return Math.round((feet * 30.48) + (inches * 2.54));
}

// Convert cm to feet/inches
export function cmToFeet(cm: number): { feet: number; inches: number } {
  const totalInches = cm / 2.54;
  const feet = Math.floor(totalInches / 12);
  const inches = Math.round(totalInches % 12);
  return { feet, inches };
}

// Convert pounds to kg
export function lbsToKg(lbs: number): number {
  return Math.round(lbs * 0.453592 * 10) / 10;
}

// Convert kg to pounds
export function kgToLbs(kg: number): number {
  return Math.round(kg / 0.453592);
}

// Calculate BMR using Mifflin-St Jeor equation
function calculateBMR(weightKg: number, heightCm: number, age: number, sex: 'male' | 'female' | 'prefer_not_to_say'): number {
  // Base calculation (assuming moderate activity multiplier of 1.55)
  let bmr: number;
  
  if (sex === 'male') {
    bmr = (10 * weightKg) + (6.25 * heightCm) - (5 * age) + 5;
  } else if (sex === 'female') {
    bmr = (10 * weightKg) + (6.25 * heightCm) - (5 * age) - 161;
  } else {
    // Average of male and female for non-specified
    const maleBmr = (10 * weightKg) + (6.25 * heightCm) - (5 * age) + 5;
    const femaleBmr = (10 * weightKg) + (6.25 * heightCm) - (5 * age) - 161;
    bmr = (maleBmr + femaleBmr) / 2;
  }
  
  // Apply moderate activity multiplier
  return Math.round(bmr * 1.55);
}

// Generate auto goals based on body profile
export function generateAutoGoals(profile: BodyProfile): AutoGeneratedGoals | null {
  if (!profile.age || !profile.heightCm || !profile.weightKg || !profile.goal) {
    return null;
  }
  
  const sex = profile.sex || 'prefer_not_to_say';
  const maintenance = calculateBMR(profile.weightKg, profile.heightCm, profile.age, sex);
  const weightLbs = kgToLbs(profile.weightKg);
  
  let calories: number;
  let protein: number;
  let fiber: number;
  let sugarLimit: number;
  
  if (profile.goal === 'bulking') {
    // Bulking: maintenance + 250-350 calories
    calories = maintenance + 300;
    // Protein: 0.7-0.9g per lb of body weight
    protein = Math.round(weightLbs * 0.8);
    // Fiber: 25-35g/day
    fiber = 30;
    // Sugar: <10-12% of total calories
    sugarLimit = Math.round((calories * 0.11) / 4); // 4 cal per g of sugar
  } else if (profile.goal === 'cutting') {
    // Cutting: maintenance - 300-400 calories
    calories = maintenance - 350;
    // Protein: 0.8-1.0g per lb of body weight
    protein = Math.round(weightLbs * 0.9);
    // Fiber: 30-40g/day
    fiber = 35;
    // Sugar: <10-12% of total calories
    sugarLimit = Math.round((calories * 0.10) / 4);
  } else {
    // Maintain
    calories = maintenance;
    protein = Math.round(weightLbs * 0.8);
    fiber = 30;
    sugarLimit = Math.round((calories * 0.10) / 4);
  }
  
  const autoGoals: AutoGeneratedGoals = {
    calories,
    protein,
    fiber,
    sugarLimit,
    generatedAt: Date.now(),
    basedOn: profile,
  };
  
  return autoGoals;
}

// Save auto-generated goals
export function saveAutoGoals(goals: AutoGeneratedGoals): void {
  localStorage.setItem(AUTO_GOALS_KEY, JSON.stringify(goals));
}

// Get auto-generated goals
export function getAutoGoals(): AutoGeneratedGoals | null {
  const stored = localStorage.getItem(AUTO_GOALS_KEY);
  if (!stored) return null;
  try {
    return JSON.parse(stored);
  } catch {
    return null;
  }
}

// Accept auto goals
export function acceptAutoGoals(): AutoGeneratedGoals | null {
  const goals = getAutoGoals();
  if (!goals) return null;
  
  goals.acceptedAt = Date.now();
  saveAutoGoals(goals);
  return goals;
}

// Check if body profile is complete for goal generation
export function isBodyProfileComplete(profile: BodyProfile | null): boolean {
  if (!profile) return false;
  return !!(profile.age && profile.heightCm && profile.weightKg && profile.goal);
}

// Disclaimer text
export const GOAL_DISCLAIMER = `These targets are estimates based on your inputs and are not medical or professional advice. Results may vary. Consult a professional for personalized guidance.`;
