// Body Goals and Auto-Goal Generation for Melius — encrypted storage

import { getEncryptedJSON, setEncryptedJSON, removeEncrypted } from './encryptedStorage';

const BODY_PROFILE_KEY = 'melius-body-profile';
const AUTO_GOALS_KEY = 'melius-auto-goals';

export interface BodyProfile {
  age?: number;
  heightCm?: number;
  weightKg?: number;
  sex?: 'male' | 'female' | 'prefer_not_to_say';
  goal?: 'bulking' | 'cutting' | 'maintain';
  useImperial?: boolean;
  createdAt?: number;
  updatedAt?: number;
}

export interface AutoGeneratedGoals {
  calories: number;
  protein: number;
  fiber: number;
  sugarLimit: number;
  generatedAt: number;
  acceptedAt?: number;
  basedOn: BodyProfile;
}

// ─── Public API ────────────────────────────────────────────────────

export async function getBodyProfile(): Promise<BodyProfile | null> {
  return getEncryptedJSON<BodyProfile | null>(BODY_PROFILE_KEY, null);
}

export async function saveBodyProfile(profile: Partial<BodyProfile>): Promise<BodyProfile> {
  const existing = (await getBodyProfile()) || {};
  const updated: BodyProfile = {
    ...existing,
    ...profile,
    updatedAt: Date.now(),
    createdAt: existing.createdAt || Date.now(),
  };
  await setEncryptedJSON(BODY_PROFILE_KEY, updated);
  return updated;
}

export async function deleteBodyProfile(): Promise<void> {
  await removeEncrypted(BODY_PROFILE_KEY);
  await removeEncrypted(AUTO_GOALS_KEY);
}

// Unit conversions
export function feetToCm(feet: number, inches: number): number { return Math.round(feet * 30.48 + inches * 2.54); }
export function cmToFeet(cm: number): { feet: number; inches: number } { const t = cm / 2.54; return { feet: Math.floor(t / 12), inches: Math.round(t % 12) }; }
export function lbsToKg(lbs: number): number { return Math.round(lbs * 0.453592 * 10) / 10; }
export function kgToLbs(kg: number): number { return Math.round(kg / 0.453592); }

function calculateBMR(weightKg: number, heightCm: number, age: number, sex: 'male' | 'female' | 'prefer_not_to_say'): number {
  let bmr: number;
  if (sex === 'male') bmr = 10 * weightKg + 6.25 * heightCm - 5 * age + 5;
  else if (sex === 'female') bmr = 10 * weightKg + 6.25 * heightCm - 5 * age - 161;
  else bmr = ((10 * weightKg + 6.25 * heightCm - 5 * age + 5) + (10 * weightKg + 6.25 * heightCm - 5 * age - 161)) / 2;
  return Math.round(bmr * 1.55);
}

export function generateAutoGoals(profile: BodyProfile): AutoGeneratedGoals | null {
  if (!profile.age || !profile.heightCm || !profile.weightKg || !profile.goal) return null;
  const sex = profile.sex || 'prefer_not_to_say';
  const maintenance = calculateBMR(profile.weightKg, profile.heightCm, profile.age, sex);
  const weightLbs = kgToLbs(profile.weightKg);

  let calories: number, protein: number, fiber: number, sugarLimit: number;
  if (profile.goal === 'bulking') {
    calories = maintenance + 300; protein = Math.round(weightLbs * 0.8); fiber = 30; sugarLimit = Math.round((calories * 0.11) / 4);
  } else if (profile.goal === 'cutting') {
    calories = maintenance - 350; protein = Math.round(weightLbs * 0.9); fiber = 35; sugarLimit = Math.round((calories * 0.10) / 4);
  } else {
    calories = maintenance; protein = Math.round(weightLbs * 0.8); fiber = 30; sugarLimit = Math.round((calories * 0.10) / 4);
  }

  return { calories, protein, fiber, sugarLimit, generatedAt: Date.now(), basedOn: profile };
}

export async function saveAutoGoals(goals: AutoGeneratedGoals): Promise<void> {
  await setEncryptedJSON(AUTO_GOALS_KEY, goals);
}

export async function getAutoGoals(): Promise<AutoGeneratedGoals | null> {
  return getEncryptedJSON<AutoGeneratedGoals | null>(AUTO_GOALS_KEY, null);
}

export async function acceptAutoGoals(): Promise<AutoGeneratedGoals | null> {
  const goals = await getAutoGoals();
  if (!goals) return null;
  goals.acceptedAt = Date.now();
  await saveAutoGoals(goals);
  return goals;
}

export function isBodyProfileComplete(profile: BodyProfile | null): boolean {
  if (!profile) return false;
  return !!(profile.age && profile.heightCm && profile.weightKg && profile.goal);
}

export const GOAL_DISCLAIMER = `These targets are estimates based on your inputs and are not medical or professional advice. Results may vary. Consult a professional for personalized guidance.`;
