import { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { X, Scale, Ruler, Calendar, User2, Target, Sparkles, AlertTriangle, Check } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Switch } from '@/components/ui/switch';
import { useApp } from '@/contexts/AppContext';
import { 
  BodyProfile, 
  feetToCm, 
  cmToFeet, 
  lbsToKg, 
  kgToLbs, 
  generateAutoGoals, 
  isBodyProfileComplete,
  GOAL_DISCLAIMER,
  AutoGeneratedGoals
} from '@/lib/bodyGoals';
import { toast } from 'sonner';

interface BodyProfileEditorProps {
  open: boolean;
  onClose: () => void;
}

export function BodyProfileEditor({ open, onClose }: BodyProfileEditorProps) {
  const { bodyProfile, updateBodyProfile, isPro, updateUserGoals } = useApp();
  
  const [age, setAge] = useState(bodyProfile?.age?.toString() || '');
  const [useImperial, setUseImperial] = useState(bodyProfile?.useImperial ?? true);
  
  // Height in imperial
  const [heightFeet, setHeightFeet] = useState('');
  const [heightInches, setHeightInches] = useState('');
  // Height in metric
  const [heightCm, setHeightCm] = useState(bodyProfile?.heightCm?.toString() || '');
  
  // Weight
  const [weightLbs, setWeightLbs] = useState('');
  const [weightKg, setWeightKg] = useState(bodyProfile?.weightKg?.toString() || '');
  
  const [sex, setSex] = useState<'male' | 'female'>(bodyProfile?.sex === 'male' || bodyProfile?.sex === 'female' ? bodyProfile.sex : 'male');
  const [goal, setGoal] = useState<'bulking' | 'cutting' | 'maintain'>(bodyProfile?.goal || 'maintain');
  
  const [showAutoGoals, setShowAutoGoals] = useState(false);
  const [autoGoals, setAutoGoals] = useState<AutoGeneratedGoals | null>(null);

  // Initialize from body profile
  useEffect(() => {
    if (bodyProfile) {
      setAge(bodyProfile.age?.toString() || '');
      setUseImperial(bodyProfile.useImperial ?? true);
      setSex(bodyProfile.sex || 'prefer_not_to_say');
      setGoal(bodyProfile.goal || 'maintain');
      
      if (bodyProfile.heightCm) {
        setHeightCm(bodyProfile.heightCm.toString());
        const { feet, inches } = cmToFeet(bodyProfile.heightCm);
        setHeightFeet(feet.toString());
        setHeightInches(inches.toString());
      }
      
      if (bodyProfile.weightKg) {
        setWeightKg(bodyProfile.weightKg.toString());
        setWeightLbs(kgToLbs(bodyProfile.weightKg).toString());
      }
    }
  }, [bodyProfile, open]);

  const handleSaveProfile = () => {
    const ageNum = parseInt(age, 10);
    if (age && (isNaN(ageNum) || ageNum < 13 || ageNum > 120)) {
      toast.error('Please enter a valid age (13-120)');
      return;
    }

    let heightCmValue: number | undefined;
    let weightKgValue: number | undefined;

    if (useImperial) {
      const feet = parseInt(heightFeet, 10) || 0;
      const inches = parseInt(heightInches, 10) || 0;
      if (feet > 0 || inches > 0) {
        heightCmValue = feetToCm(feet, inches);
      }
      const lbs = parseFloat(weightLbs);
      if (!isNaN(lbs) && lbs > 0) {
        weightKgValue = lbsToKg(lbs);
      }
    } else {
      const cm = parseFloat(heightCm);
      if (!isNaN(cm) && cm > 0) {
        heightCmValue = cm;
      }
      const kg = parseFloat(weightKg);
      if (!isNaN(kg) && kg > 0) {
        weightKgValue = kg;
      }
    }

    const profile: Partial<BodyProfile> = {
      age: ageNum || undefined,
      heightCm: heightCmValue,
      weightKg: weightKgValue,
      sex,
      goal,
      useImperial,
    };

    updateBodyProfile(profile);
    toast.success('Body profile saved!');

    // Check if we can generate auto goals
    if (isPro && isBodyProfileComplete({ ...bodyProfile, ...profile } as BodyProfile)) {
      const goals = generateAutoGoals({ ...bodyProfile, ...profile } as BodyProfile);
      if (goals) {
        setAutoGoals(goals);
        setShowAutoGoals(true);
      }
    }
  };

  const handleAcceptAutoGoals = () => {
    if (!autoGoals) return;
    
    updateUserGoals({
      calories: autoGoals.calories,
      protein: autoGoals.protein,
      fiber: autoGoals.fiber,
      sugar: autoGoals.sugarLimit,
    });
    
    toast.success('Goals updated based on your profile!');
    setShowAutoGoals(false);
    onClose();
  };

  return (
    <AnimatePresence>
      {open && (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          className="fixed inset-0 z-[100] bg-background overflow-y-auto"
        >
          {/* Header */}
          <div className="sticky top-0 bg-background/95 backdrop-blur-sm px-6 pt-8 pb-4 safe-top border-b border-border/50 z-10">
            <div className="flex items-center justify-between">
              <div>
                <h1 className="text-2xl font-bold">Personalized Goals</h1>
                <p className="text-muted-foreground text-sm">Your physical info for personalized goals</p>
              </div>
              <Button variant="ghost" size="icon" onClick={onClose} className="rounded-xl">
                <X className="w-5 h-5" />
              </Button>
            </div>
          </div>

          <div className="p-6 pb-32 space-y-6">
            {/* Unit Toggle */}
            <div className="flex items-center justify-between p-4 bg-secondary/30 rounded-xl">
              <span className="font-medium">Use Imperial (lbs/ft)</span>
              <Switch checked={useImperial} onCheckedChange={setUseImperial} />
            </div>

            {/* Age */}
            <div className="bg-card rounded-2xl p-5 border border-border/50">
              <div className="flex items-center gap-2 mb-4">
                <Calendar className="w-5 h-5 text-primary" />
                <Label className="text-xs font-bold text-muted-foreground uppercase tracking-wide">Age</Label>
              </div>
              <Input
                type="number"
                inputMode="numeric"
                placeholder="e.g., 25"
                value={age}
                onChange={(e) => setAge(e.target.value)}
                className="h-12 text-lg rounded-xl bg-secondary/50 border-0"
              />
            </div>

            {/* Height */}
            <div className="bg-card rounded-2xl p-5 border border-border/50">
              <div className="flex items-center gap-2 mb-4">
                <Ruler className="w-5 h-5 text-primary" />
                <Label className="text-xs font-bold text-muted-foreground uppercase tracking-wide">Height</Label>
              </div>
              {useImperial ? (
                <div className="grid grid-cols-2 gap-3">
                  <div>
                    <Label className="text-xs text-muted-foreground">Feet</Label>
                    <Input
                      type="number"
                      inputMode="numeric"
                      placeholder="5"
                      value={heightFeet}
                      onChange={(e) => setHeightFeet(e.target.value)}
                      className="h-12 text-lg rounded-xl bg-secondary/50 border-0 mt-1"
                    />
                  </div>
                  <div>
                    <Label className="text-xs text-muted-foreground">Inches</Label>
                    <Input
                      type="number"
                      inputMode="numeric"
                      placeholder="10"
                      value={heightInches}
                      onChange={(e) => setHeightInches(e.target.value)}
                      className="h-12 text-lg rounded-xl bg-secondary/50 border-0 mt-1"
                    />
                  </div>
                </div>
              ) : (
                <Input
                  type="number"
                  inputMode="numeric"
                  placeholder="e.g., 178"
                  value={heightCm}
                  onChange={(e) => setHeightCm(e.target.value)}
                  className="h-12 text-lg rounded-xl bg-secondary/50 border-0"
                />
              )}
            </div>

            {/* Weight */}
            <div className="bg-card rounded-2xl p-5 border border-border/50">
              <div className="flex items-center gap-2 mb-4">
                <Scale className="w-5 h-5 text-primary" />
                <Label className="text-xs font-bold text-muted-foreground uppercase tracking-wide">
                  Weight ({useImperial ? 'lbs' : 'kg'})
                </Label>
              </div>
              <Input
                type="number"
                inputMode="decimal"
                placeholder={useImperial ? 'e.g., 160' : 'e.g., 72'}
                value={useImperial ? weightLbs : weightKg}
                onChange={(e) => useImperial ? setWeightLbs(e.target.value) : setWeightKg(e.target.value)}
                className="h-12 text-lg rounded-xl bg-secondary/50 border-0"
              />
            </div>

            {/* Sex */}
            <div className="bg-card rounded-2xl p-5 border border-border/50">
              <div className="flex items-center gap-2 mb-4">
                <User2 className="w-5 h-5 text-primary" />
                <Label className="text-xs font-bold text-muted-foreground uppercase tracking-wide">Sex</Label>
              </div>
              <div className="grid grid-cols-3 gap-2">
                {(['male', 'female', 'prefer_not_to_say'] as const).map((option) => (
                  <button
                    key={option}
                    onClick={() => setSex(option)}
                    className={`py-3 px-2 rounded-xl font-medium text-sm transition-all border ${
                      sex === option
                        ? 'bg-primary text-primary-foreground border-primary'
                        : 'bg-secondary/50 text-secondary-foreground border-border/50 hover:bg-secondary'
                    }`}
                  >
                    {option === 'prefer_not_to_say' ? 'Skip' : option.charAt(0).toUpperCase() + option.slice(1)}
                  </button>
                ))}
              </div>
            </div>

            {/* Goal */}
            <div className="bg-card rounded-2xl p-5 border border-border/50">
              <div className="flex items-center gap-2 mb-4">
                <Target className="w-5 h-5 text-primary" />
                <Label className="text-xs font-bold text-muted-foreground uppercase tracking-wide">Your Goal</Label>
              </div>
              <div className="grid grid-cols-3 gap-2">
                {([
                  { value: 'bulking', label: 'Bulk', desc: 'Gain muscle' },
                  { value: 'maintain', label: 'Maintain', desc: 'Stay same' },
                  { value: 'cutting', label: 'Cut', desc: 'Lose fat' },
                ] as const).map((option) => (
                  <button
                    key={option.value}
                    onClick={() => setGoal(option.value)}
                    className={`py-3 px-2 rounded-xl transition-all border text-center ${
                      goal === option.value
                        ? 'bg-primary text-primary-foreground border-primary'
                        : 'bg-secondary/50 text-secondary-foreground border-border/50 hover:bg-secondary'
                    }`}
                  >
                    <span className="font-semibold text-sm block">{option.label}</span>
                    <span className="text-[10px] opacity-70">{option.desc}</span>
                  </button>
                ))}
              </div>
            </div>

            {/* Pro Feature Notice */}
            {!isPro && (
              <div className="bg-gradient-to-r from-amber-500/10 to-orange-500/10 rounded-2xl p-4 border border-amber-500/20">
                <div className="flex items-start gap-3">
                  <Sparkles className="w-5 h-5 text-amber-500 flex-shrink-0 mt-0.5" />
                  <div>
                    <p className="font-semibold text-amber-600 dark:text-amber-400">Pro Feature</p>
                    <p className="text-sm text-muted-foreground mt-1">
                      Upgrade to MeliusMe Pro to get personalized calorie, protein, fiber, and sugar goals based on your profile.
                    </p>
                  </div>
                </div>
              </div>
            )}
          </div>

          {/* Save Button */}
          <div className="fixed bottom-0 left-0 right-0 p-4 bg-background border-t border-border/50 safe-bottom">
            <Button onClick={handleSaveProfile} className="w-full h-12 rounded-xl font-bold">
              Save Profile
            </Button>
          </div>

          {/* Auto Goals Modal */}
          <AnimatePresence>
            {showAutoGoals && autoGoals && (
              <motion.div
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
                className="fixed inset-0 z-[110] bg-black/80 flex items-center justify-center p-6"
                onClick={() => setShowAutoGoals(false)}
              >
                <motion.div
                  initial={{ scale: 0.9, opacity: 0 }}
                  animate={{ scale: 1, opacity: 1 }}
                  exit={{ scale: 0.9, opacity: 0 }}
                  onClick={(e) => e.stopPropagation()}
                  className="w-full max-w-md bg-background rounded-3xl p-6 shadow-2xl"
                >
                  <div className="flex items-center gap-3 mb-6">
                    <div className="w-12 h-12 bg-primary/20 rounded-xl flex items-center justify-center">
                      <Sparkles className="w-6 h-6 text-primary" />
                    </div>
                    <div>
                      <h3 className="text-lg font-bold">Your Personalized Goals</h3>
                      <p className="text-sm text-muted-foreground">Based on your profile</p>
                    </div>
                  </div>

                  <div className="space-y-3 mb-6">
                    <div className="flex justify-between p-3 bg-secondary/50 rounded-xl">
                      <span className="text-muted-foreground">Daily Calories</span>
                      <span className="font-bold">{autoGoals.calories} cal</span>
                    </div>
                    <div className="flex justify-between p-3 bg-secondary/50 rounded-xl">
                      <span className="text-muted-foreground">Protein</span>
                      <span className="font-bold">{autoGoals.protein}g</span>
                    </div>
                    <div className="flex justify-between p-3 bg-secondary/50 rounded-xl">
                      <span className="text-muted-foreground">Fiber</span>
                      <span className="font-bold">{autoGoals.fiber}g</span>
                    </div>
                    <div className="flex justify-between p-3 bg-secondary/50 rounded-xl">
                      <span className="text-muted-foreground">Sugar Limit</span>
                      <span className="font-bold">{autoGoals.sugarLimit}g</span>
                    </div>
                  </div>

                  <div className="bg-warning/10 border border-warning/20 rounded-xl p-3 mb-6">
                    <div className="flex gap-2">
                      <AlertTriangle className="w-4 h-4 text-warning flex-shrink-0 mt-0.5" />
                      <p className="text-xs text-muted-foreground">{GOAL_DISCLAIMER}</p>
                    </div>
                  </div>

                  <div className="grid grid-cols-2 gap-3">
                    <Button variant="outline" onClick={() => setShowAutoGoals(false)} className="rounded-xl">
                      Cancel
                    </Button>
                    <Button onClick={handleAcceptAutoGoals} className="rounded-xl">
                      <Check className="w-4 h-4 mr-2" />
                      Accept
                    </Button>
                  </div>
                </motion.div>
              </motion.div>
            )}
          </AnimatePresence>
        </motion.div>
      )}
    </AnimatePresence>
  );
}
